### ISSUE TITLE
Server fails to decrypt seed with jolocom-lib >= 2.5.0

### ISSUE THREAD

**Issue by laurogripa** [jolocom/demo-sso#18]
Hey!

I was able to run the application with `yarn start` but I got an `UnhandledPromiseRejectionWarning`:

```
(node:11092) UnhandledPromiseRejectionWarning: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipher.final (internal/crypto/cipher.js:164:28)
    at Function.decrypt (/home/lauro/code/demo-sso/node_modules/jolocom-lib/ts/vaultedKeyProvider/softwareProvider.ts:182:59)
    at SoftwareKeyProvider.getPublicKey (/home/lauro/code/demo-sso/node_modules/jolocom-lib/ts/vaultedKeyProvider/softwareProvider.ts:59:38)
    at JolocomRegistry.authenticate (/home/lauro/code/demo-sso/node_modules/jolocom-lib/ts/registries/jolocomRegistry.ts:192:50)
    at Object.<anonymous> (/home/lauro/code/demo-sso/server/server.ts:25:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/home/lauro/code/demo-sso/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/lauro/code/demo-sso/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at Object.<anonymous> (/home/lauro/code/demo-sso/node_modules/ts-node/src/_bin.ts:177:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

I was still able to view the page on `localhost:9000`, but when I click on `continue with jolocom`, I get the following error on console:
```
GET http://localhost:9000/socket.io/?userId=gjhrr&EIO=3&transport=polling&t=MnKy_eG 404 (Not Found)
```

I didn't edit anything on `config.ts`, left it all as default.

Any suggestions?

**Comment by mnzaki** [comment]
@laurogripa thanks for the report, I've pinned down the issue to a recent update we made to the library, we'll be fixing this very soon!

In the meantime, you can try to downgrade `jolocom-lib` to get things working quickly for now:
`$ yarn add jolocom-lib@\<2.5.0`

**Comment by laurogripa** [comment]
I tested your referenced PR and it worked for me. Thanks! :tada:
